### ISSUE TITLE
来自NGA，感恩大佬

### ISSUE THREAD

**Issue by lucenli** [winrey/pcr-wiki-helper#1]
感谢大佬做的产品，太棒了！

有一个小疑惑，同样的数据，这个计算结果和之前用的exe版本有些许不同。是因为算法不一致吗

**Comment by winrey** [comment]
> 感谢大佬做的产品，太棒了！
> 
> 有一个小疑惑，同样的数据，这个计算结果和之前用的exe版本有些许不同。是因为算法不一致吗

emmmmm....
exe版本有两个，不造你说的是哪个，，
其中一个算法没有公开，据说是贪心；另一个是线性规划。
线性规划的解法是一致的。（`推荐`列）
但是贪心那个是我的猜测。
实际上这个算法是把贪心和线性规划结合在一起用的。线性规划决定总次数，贪心决定刷本次序。

**Comment by lucenli** [comment]
![image](https://user-images.githubusercontent.com/16946496/81139195-7ab90180-8f97-11ea-8ea8-48657880a801.png)
是这个，我也不知道是哪种算法，似乎是线性？
感觉差别还是有的，尽管不大

**Comment by lucenli** [comment]
哦大概懂了，他这个建议次数是期望次数的80%而已，如果看期望次数确实是几乎一样的解答

区别在于最后那个素材，6-14和9-1都是36%的掉率，一个选了前者一个后者，倒也没什么大的区别

是这样吧

**Comment by lucenli** [comment]
另外问一下，nga的帖子似乎不见了，我想安利小伙伴，但是似乎他们不太会用，还有别的地方有介绍吗

**Comment by winrey** [comment]
> ![image](https://user-images.githubusercontent.com/16946496/81139195-7ab90180-8f97-11ea-8ea8-48657880a801.png)
> 是这个，我也不知道是哪种算法，似乎是线性？
> 感觉差别还是有的，尽管不大

其实我感觉原因应该是，之前那个exe没考虑体力消耗不太一样……？虽然也没差多少

**Comment by winrey** [comment]
> 另外问一下，nga的帖子似乎不见了，我想安利小伙伴，但是似乎他们不太会用，还有别的地方有介绍吗

已经找版主恢复啦！
