### ISSUE TITLE
大佬nb，报两个bug

### ISSUE THREAD

**Issue by ESoapW** [winrey/pcr-wiki-helper#2]
-进入Armory页面后必须刷新一次，然后插件才能跑得起来
-修改倍数和计算结果点了都没用，已试过重启浏览器和系统

环境：
Safari 13.0.5 (15608.5.11)   TamperMonkey v4.10.6108

**Comment by ESoapW** [comment]
Update:换chrome试了一下是可以用的

**Comment by winrey** [comment]
看来Safari和Firefox都有一些兼容性问题，等我抽空看看到底哪里报错了

**Comment by winrey** [comment]
坑爹了，safari的应用商店我就没下成功TamperMonkey插件本体。。
应该是有什么语言特性Safari不支持吧
刷新那个问题是TamperMonkey的问题，估计是改不了了，只能提示一下用户
