### ISSUE TITLE
有个新的需求

### ISSUE THREAD

**Issue by winlaic** [winrey/pcr-wiki-helper#22]
大佬好！使用的时候发现个新的需求：**装备的来源并不仅仅是刷图，公会赠送也是一个来源。**
我粗略想了想有个可能的解决方案，鄙人才疏学浅，如有错误还望指出！

线性规划的结果虽然是最优的，但是按照这个结果刷装备还是会溢出，这是因为一定会有装备是短板，为了弥补这个短板有些装备要被迫多刷。所以按照计算结果刷图，刷图的结果中**最终溢出最少的装备应该就是短板装备**，可以把这些装备提示出来，在公会中要这些装备。

**Comment by cool-delete** [comment]
@winlaic 目前已有标识溢出最少的了 就是当前地图列表里面的黄色装备，意思是当前结果只有这个地图是唯一能出的 详细的话情况说明
