### ISSUE TITLE
计算结果界面的快速修改功能未正常运作

### ISSUE THREAD

**Issue by NeuWings** [winrey/pcr-wiki-helper#25]
在计算结果浮窗选择快速修改并进行数量修改后回车,碎片数量没有变动.
Edge 85.0.564.8
油猴最新+脚本版本最新
<details>
<summary>图片实例折叠</summary>

![快速修改](https://user-images.githubusercontent.com/26756868/87652958-6d827500-c787-11ea-9563-6d617822fb94.png)
![数量变动](https://user-images.githubusercontent.com/26756868/87652968-707d6580-c787-11ea-8f89-522ab2bf0e86.png)

回车后数量依旧为89,变动并未反馈.
</details>

**Comment by cool-delete** [comment]
收到 已修复 等待 @winrey 合并更新就行了 谢谢提交
