### ISSUE TITLE
泥潭大佬 提一个建议

### ISSUE THREAD

**Issue by cool-delete** [winrey/pcr-wiki-helper#3]
按照使用说明 完成适用和推荐的最小值后修改装备数量 这步有点不妥 因为你的计算按钮按下后 是轮番计算地图的 每次过程都需要好几秒的时间 可是我没有修改数量的时候只是关闭窗口 想再看的话脚本还是会再跑一次的 能加一个按钮和表示 显示当前数据和重新计算么

**Comment by cool-delete** [comment]
还有就是 需要修改数量的时候 能不能在窗口里面直接修改呢 计算后的关卡排列和图书馆自带的不一样 这样完成最小值后就可以直接快速修改了

**Comment by winrey** [comment]
其实这有另外一个办法，就是关卡的名字是可以点击的，点击后会自动跳到对应位置
等我在下面再加一个“快速修改”按钮就解决啦～

**Comment by winrey** [comment]
已经完成，即将更新
