### ISSUE TITLE
计算结果页编辑数量不可用

### ISSUE THREAD

**Issue by zayomeng** [winrey/pcr-wiki-helper#31]
图书馆又更新了 布局有较大变化

**Comment by zayomeng** [comment]
经测试 bug可以复现 大概的问题和[https://github.com/winrey/pcr-wiki-helper/issues/24](url) 这个24issue中我之前提到的是一样的 个人猜测问题所在是图书馆更新后点击快速修改之后新增的弹窗

**Comment by cool-delete** [comment]
@NamakoNeko 刚刚实测没复现啊 你的版本是2.60.1么
