### ISSUE TITLE
关于算法的一些建议

### ISSUE THREAD

**Issue by chaoscard** [winrey/pcr-wiki-helper#32]
如图，我缺月光之杖，进度9/160，在规划结果中有两张地图可刷。分别是8-12和6-14，详情如下图：
![d1O49P.png](https://s1.ax1x.com/2020/08/19/d1O49P.png)
![d1Ofht.png](https://s1.ax1x.com/2020/08/19/d1Ofht.png)
8-12推荐刷55或13，6-14推荐刷140或128
那么问题来了：
第一，即使考虑到按照规划月桂树会溢出，但是月桂树本身是孤儿装备，多屯一些总是没错的；
第二，从玛娜看8-12也明显比6-14收益高。
所以无论从装备还是玛娜看，多刷8-12都是更优的，但是规划却给的很离谱？
请问这个问题有办法解决吗？
我想到了一些方法，我不懂程序，仅给大佬提供些想法：
一、在算法中加入孤儿装优先级，比如冰之大剑、月桂树、新月的叹息这些，在计算保证所需装备的条件下，优先刷副产物有孤儿装的图；
二、玛娜优先，在计算保证所需装备的条件下，优先刷玛娜多的图；
三、直接在算法中忽略效率为36%的图，转而去刷其他能刷规划中其他已经溢出但是需求量大的图（其实就是第一第二条结合）。

**Comment by cool-delete** [comment]
不太明白 你说的规划离谱是指结果给出了6-14吗?
如果是的话 其实没问题的 你往后打的话 6-14会自然消失
其实碎片数稍微改一下的话 排序也会不一样的
