### ISSUE TITLE
有可能把37图的孤儿装掉落考虑进去吗？

### ISSUE THREAD

**Issue by gy6221** [winrey/pcr-wiki-helper#34]
如题，计算效率时可以加上37的孤儿装随机掉落吗？
现在的效率看着感觉不那么直观

**Comment by cool-delete** [comment]
37的孤儿装备是指哪个啊 37图?

**Comment by gy6221** [comment]
> 37的孤儿装备是指哪个啊 37图?

是的，37图

**Comment by cool-delete** [comment]
不是很明白你说的加上随机掉落的意识

**Comment by gy6221** [comment]
37图除了主掉落和副掉落以外还增加了16个孤儿装的随机掉落
所以理论上37图的实际刷图效率应该会比目前只考虑主掉落和副掉落的计算结果要高一些？

**Comment by cool-delete** [comment]
https://pcredivewiki.tw/Map/Detail/%E3%83%B4%E3%82%A7%E3%83%BC%E3%83%8A%E6%B9%96%E7%95%94%E9%81%93%E3%83%BB%E5%8C%97%E9%83%A8N
里面我找不到孤儿装的随机掉落数据喔

**Comment by gy6221** [comment]
是的，这部分的掉落数据好像确实在图书馆没有，日站wiki有提到。如果要实现的话可能需要hard code。这实现方式确实有点恶心。

具体位置是这个页面“一部の金枠/紫枠装備のドロップ追加”这部分的折叠内容内
https://gamewith.jp/pricone-re/article/show/222868。

**Comment by cool-delete** [comment]
你的网址 404了..
等图书馆作者反馈吧 他加上的话 这边就加上了 不然会冲突
