### ISSUE TITLE
大佬，界面里的保存修改失效了

### ISSUE THREAD

**Issue by muwing76** [winrey/pcr-wiki-helper#38]
点击时不会进行保存修改

**Comment by cool-delete** [comment]
....复现一下?

**Comment by muwing76** [comment]
复现是啥 在2020年09月16日 09:14，colin 写道： 

....复现一下?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/winrey/pcr-wiki-helper/issues/38#issuecomment-693111741",

"url": "https://github.com/winrey/pcr-wiki-helper/issues/38#issuecomment-693111741",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by cool-delete** [comment]
.....别费劲了 更新最新版吧
