### ISSUE TITLE
图书馆更换新UI后，弹出类计算页面的快速修改功能无法使用

### ISSUE THREAD

**Issue by GodofTheFallen** [winrey/pcr-wiki-helper#40]
情况如图所示，没有输入框
![image](https://user-images.githubusercontent.com/15105315/103363960-6feb4800-4af7-11eb-8d0b-c2ef91951721.png)

**Comment by kokoronoinori** [comment]
疑似快速修改关联有误，见图片，点击快速修改后，原网页额外掉落图标出现黑框
![Screenshot from 2021-01-08 06-20-30](https://user-images.githubusercontent.com/22474937/103951642-0b289100-517a-11eb-9bea-385f69221918.png)
![Screenshot from 2021-01-08 06-20-49](https://user-images.githubusercontent.com/22474937/103951654-111e7200-517a-11eb-82c8-9461c4bb9eb1.png)

**Comment by GodofTheFallen** [comment]
将脚本第390行的：
`document.querySelector('#app div.p-2.text-center.mapDrop-item.mr-2 input.form-control') || findOnePCRelem('table span button', '快速修改').click();`
改为
`document.querySelector('#app div.p-2.text-center.mapDrop-item.mr-2 input.form-control') || findOnePCRelem('table button', '快速修改').click();`
可以解决该问题
