### ISSUE TITLE
弹出的窗口无法影响道具栏的内容数量

### ISSUE THREAD

**Issue by gotofandian** [winrey/pcr-wiki-helper#42]
没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……

**Comment by cool-delete** [comment]
> 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……

没有吧? 你浏览器是什么 版本号是多少

**Comment by gotofandian** [comment]
> > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> 
> 没有吧? 你浏览器是什么 版本号是多少

360极速 13.0.2206.0

**Comment by cool-delete** [comment]
> > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > 
> > 
> > 没有吧? 你浏览器是什么 版本号是多少
> 
> 360极速 13.0.2206.0
脚本的版本呢

**Comment by gotofandian** [comment]
> > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > 
> > > 
> > > 没有吧? 你浏览器是什么 版本号是多少
> > 
> > 
> > 360极速 13.0.2206.0
> > 脚本的版本呢

3.1.0了

**Comment by cool-delete** [comment]
> > > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > > 
> > > > 
> > > > 没有吧? 你浏览器是什么 版本号是多少
> > > 
> > > 
> > > 360极速 13.0.2206.0
> > > 脚本的版本呢
> 
> 3.1.0了

按下f12看看红色err的信息 截图过来看看吧

**Comment by gotofandian** [comment]
> > > > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > > > 
> > > > > 
> > > > > 没有吧? 你浏览器是什么 版本号是多少
> > > > 
> > > > 
> > > > 360极速 13.0.2206.0
> > > > 脚本的版本呢
> > 
> > 
> > 3.1.0了
> 
> 按下f12看看红色err的信息 截图过来看看吧

https://www.hualigs.cn/image/6042bfedb808f.jpg
这里吗

**Comment by cool-delete** [comment]
> > > > > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > > > > 
> > > > > > 
> > > > > > 没有吧? 你浏览器是什么 版本号是多少
> > > > > 
> > > > > 
> > > > > 360极速 13.0.2206.0
> > > > > 脚本的版本呢
> > > 
> > > 
> > > 3.1.0了
> > 
> > 
> > 按下f12看看红色err的信息 截图过来看看吧
> 
> https://www.hualigs.cn/image/6042bfedb808f.jpg
> 这里吗

就这些吗 ? 你完整操作后再截图吧

**Comment by gotofandian** [comment]
> > > > > > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > > > > > 
> > > > > > > 
> > > > > > > 没有吧? 你浏览器是什么 版本号是多少
> > > > > > 
> > > > > > 
> > > > > > 360极速 13.0.2206.0
> > > > > > 脚本的版本呢
> > > > 
> > > > 
> > > > 3.1.0了
> > > 
> > > 
> > > 按下f12看看红色err的信息 截图过来看看吧
> > 
> > 
> > https://www.hualigs.cn/image/6042bfedb808f.jpg
> > 这里吗
> 
> 就这些吗 ? 你完整操作后再截图吧

在弹窗出现后截图的这些内容 只看到了这些err 或者您需要什么样的操作步骤 我录个视频发过来

**Comment by cool-delete** [comment]
输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了

> > > > > > > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 没有吧? 你浏览器是什么 版本号是多少
> > > > > > > 
> > > > > > > 
> > > > > > > 360极速 13.0.2206.0
> > > > > > > 脚本的版本呢
> > > > > 
> > > > > 
> > > > > 3.1.0了
> > > > 
> > > > 
> > > > 按下f12看看红色err的信息 截图过来看看吧
> > > 
> > > 
> > > https://www.hualigs.cn/image/6042bfedb808f.jpg
> > > 这里吗
> > 
> > 
> > 就这些吗 ? 你完整操作后再截图吧
> 
> 在弹窗出现后截图的这些内容 只看到了这些err 或者您需要什么样的操作步骤 我录个视频发过来

就这步哦

**Comment by cool-delete** [comment]
> > > > > > > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 没有吧? 你浏览器是什么 版本号是多少
> > > > > > > 
> > > > > > > 
> > > > > > > 360极速 13.0.2206.0
> > > > > > > 脚本的版本呢
> > > > > 
> > > > > 
> > > > > 3.1.0了
> > > > 
> > > > 
> > > > 按下f12看看红色err的信息 截图过来看看吧
> > > 
> > > 
> > > https://www.hualigs.cn/image/6042bfedb808f.jpg
> > > 这里吗
> > 
> > 
> > 就这些吗 ? 你完整操作后再截图吧
> 
> 在弹窗出现后截图的这些内容 只看到了这些err 或者您需要什么样的操作步骤 我录个视频发过来

在我脚本里面 按下回车后并不会立刻同步到主界面的 因为同步到界面会很卡 但是会同步到数据库 这样不卡 而且就算你断网了刷新也没关系 
而且关闭弹窗后 也是会同步到主界面的

**Comment by gotofandian** [comment]
> > > > > > > > > > 没法像以前一样直接在弹出的窗口里快速修改了 输入新增数量后按下回车虽然总量在弹窗中会变但是并不会影响道具栏里面的数量 也不会自动切到下一个道具的输入栏里了……
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 没有吧? 你浏览器是什么 版本号是多少
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 360极速 13.0.2206.0
> > > > > > > > 脚本的版本呢
> > > > > > 
> > > > > > 
> > > > > > 3.1.0了
> > > > > 
> > > > > 
> > > > > 按下f12看看红色err的信息 截图过来看看吧
> > > > 
> > > > 
> > > > https://www.hualigs.cn/image/6042bfedb808f.jpg
> > > > 这里吗
> > > 
> > > 
> > > 就这些吗 ? 你完整操作后再截图吧
> > 
> > 
> > 在弹窗出现后截图的这些内容 只看到了这些err 或者您需要什么样的操作步骤 我录个视频发过来
> 
> 在我脚本里面 按下回车后并不会立刻同步到主界面的 因为同步到界面会很卡 但是会同步到数据库 这样不卡 而且就算你断网了刷新也没关系
> 而且关闭弹窗后 也是会同步到主界面的

就是说现在其实并没有出现问题 等在弹窗里输入完按关闭后他就会结算进道具库了是吗……？那麻烦了TvT

**Comment by cool-delete** [comment]
是的

**Comment by cool-delete** [comment]
> 也不会自动切到下一个道具的输入栏里了……

3.1.0会自动切到下个道具的快速输入框的啊 而且倒头了会重新回到第一项
不对吗

**Comment by gotofandian** [comment]
> > 也不会自动切到下一个道具的输入栏里了……
> 
> 3.1.0会自动切到下个道具的快速输入框的啊 而且倒头了会重新回到第一项
> 不对吗

会切 但是一旦切到黄框的独有装备后后面的格子不管你输入哪一个按了回车都会弹到第一格的输入框

**Comment by gotofandian** [comment]
> > > 也不会自动切到下一个道具的输入栏里了……
> > 
> > 
> > 3.1.0会自动切到下个道具的快速输入框的啊 而且倒头了会重新回到第一项
> > 不对吗
> 
> 会切 但是一旦切到黄框的独有装备后后面的格子不管你输入哪一个按了回车都会弹到第一格的输入框

https://www.hualigs.cn/image/6045712849b8b.jpg

**Comment by gy6221** [comment]
![](https://p.sda1.dev/1/7de3db8cb11c4140912d826e4c607322/image.png)
我也遇到了类似问题，假如通过增加方式编辑图中两个缺少的装备，仅黄框装备能正常保存，后面的装备会在重新计算后恢复原数量
