### ISSUE TITLE
希望增加导出数据的功能

### ISSUE THREAD

**Issue by chaoscard** [winrey/pcr-wiki-helper#6]
如题，一天通常很难刷完所需的装备。
浏览器不方便记录自己到底刷了多少次，如果可以把数据导出为excel表格就会方便很多。
像这样的excel就很方便
![Y5EtJJ.png](https://s1.ax1x.com/2020/05/19/Y5EtJJ.png)
希望能够导出以下数据
![Y5ENW9.png](https://s1.ax1x.com/2020/05/19/Y5ENW9.png)

**Comment by winrey** [comment]
有道理！下个版本做一下

**Comment by cool-delete** [comment]
fixed #6 on 9e1724ae32478dee89cb7d51dd708fa801e912d0
