### ISSUE TITLE
算法应该是有问题的吧...

### ISSUE THREAD

**Issue by cool-delete** [winrey/pcr-wiki-helper#9]
![image](https://user-images.githubusercontent.com/13638610/82907782-a5e0b080-9f99-11ea-897a-286cbdb58e3b.png)
我缺帽子和新月的嘆息....可是明明
![image](https://user-images.githubusercontent.com/13638610/82907998-efc99680-9f99-11ea-92f1-df70b4c85a41.png)
显示这个地图概率是56的%
可是计算结果没有显示出来啊

**Comment by winrey** [comment]
这俩截图不是不是同一张图吗。。

**Comment by cool-delete** [comment]
> 这俩截图不是不是同一张图吗。。

的确啊 56%是我偶尔发现的 5-7是我看了36%觉得概率太低了 去看了一下 才发现有个地图是56的

**Comment by 132conan** [comment]
你只缺这两种材料吗，
如果不是的话，只是因为你刷了其他本，把饰品的次数覆盖掉了吧
如果有问题的话，建议导出图书馆链接，我们可以一起确认一下。

**Comment by cool-delete** [comment]
fix 8cf9dcfa2587a0d3a6df08cf17b7c03508842390
> 你只缺这两种材料吗，
> 如果不是的话，只是因为你刷了其他本，把饰品的次数覆盖掉了吧
> 如果有问题的话，建议导出图书馆链接，我们可以一起确认一下。
